# Generated by Django 5.1.4 on 2024-12-18 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniVerse', '0002_user_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_channel',
            new_name='UserChannel',
        ),
    ]
